export const OPEN = 'minicart/OPEN'
export const CLOSE = 'minicart/CLOSE'

export const TOTAL_ITEMS = 'minicart/TOTAL_ITEMS'
export const TOTAL_VALUE = 'minicart/TOTAL_VALUE'
export const PRODUCTS = 'minicart/PRODUCTS'
export const ADD_PRODUCT = 'minicart/ADD_PRODUCT'
export const REMOVE_PRODUCT = 'minicart/REMOVE_PRODUCT'
export const INC_QUANTITY = 'minicart/INC_QUANTITY'
export const DEC_QUANTITY = 'minicart/DEC_QUANTITY'
export const TOTAL_SHIPPING = 'minicart/TOTAL_SHIPPING'
export const FREE_SHIPPING = 'minicart/FREE_SHIPPING'
export const UPDATE = 'minicart/UPDATE'